@startuml OPCIONES

skinparam classAttributeIconSize 0

abstract class Opcion{
    ~ texto:String
    
    + Opcion(texto:String, estado:Estado)
    + {abstract} contarCorrecta():int
    + {abstract} contarIncorrecta():int
    + obtenerTexto():String
}

class Grupal extends Opcion{
    - nombreGrupo:String
    - int puntosCorrecta:int
    - int puntosIncorrecta:int

    + Grupal(texto:String, nombreGrupo:String, estado:Estado)
    + actualizarEstado(opcion:Grupal)
    + obtenerGrupo():String
    + int contarCorrecta():int
    + int contarIncorrecta():int
}
class Ordenada extends Opcion{
    - posicion:int
    - puntosIncorrecta:int
    - puntosCorrecta:int

    + Ordenada(texto:String, posicion:int, estado:Estado)
    + actualizarEstado(opcion:Ordenada)
    + contarCorrecta():int
    + contarIncorrecta():int
}
class Simple {
    - estado:Estado

    + Simple(texto:String, estado:Estado)
    + contarCorrecta():int
    + contarIncorrecta():int
    + actualizarEstado(opcion:Simple)
    + tieneIgualTexto(opcionJugador:Simple):boolean
}

Opcion <|-up- Simple