@startuml ALGOHOOT3

skinparam classAttributeIconSize 0

class AlgoHoot3{
    - {static} instancia:AlgoHoot3
    - rondas:int
    - iteradorJugadores:Iterator<Jugador>
    - jugadorActual:Jugador


    + {static} obtenerInstancia():AlgoHoot3
    + iniciarAlgoHoot(jugadores:List<Jugador>, turno:Turno, \ncriterio:CriterioDeVictoria, preguntas:List<Pregunta>)
    + pasarRonda()
    + jugarTurno(opcionesElegidas:List<Opcion>, modificador:Modificador)
    + terminoLaRonda():boolean
    + obtenerRonda():int
    + obtenerPreguntaDeRondaActual():Pregunta
    + obtenerJugadorActual():Jugador
    + terminoJuego():boolean
    + jugadoresOrdenadosPorCriterio():List<Jugador>
}

interface CriterioDeVictoria{
    + establecerJugadores(jugadores:List<Jugador>)
    + jugadoresOrdenados():List<Jugador> 
    + terminoJuego(rondasJugadas:int):boolean
}

class Jugador{
    - puntaje:int;
    - nombre:String;
    - modificadores:List<Modificador>;
    
    + Jugador(nombre:String, modificadores:List<Modificador>)

    + sumarPuntaje(puntaje:int)
    + obtenerPuntaje():int
    + tieneMejorPuntajeQue(jugador:Jugador):boolean
    + usar(modificador:Modificador)
    + obtenerModificadores():List<Modificador>
    + tieneNombre(buscado:String):boolean
    + equals(jugador:Jugador):boolean
    + obtenerNombre():String
    + obtenerUltimoModificadorUsado():Modificador
}

abstract class Pregunta{
    ~ categoria:String
    ~ enunciado:String
    ~ explicacion:String
    ~ puntaje:Puntaje

    + Pregunta(enunciado:String, puntaje:Puntaje, \ncategoria:String, explicacion:String)

    + asignarPuntajes(respuestas:List<Respuesta>)
    + modificadorEsValido(modificador:Modificador):boolean
    + obtenerCategoria():String
    + obtenerEnunciado():String
    + obtenerExplicacion():String
}

class Turno{
    - respuestas:List<Respuesta>
    - preguntaDelTurno:Pregunta
    - modificador:Modificador

    + agregarRespuesta(opcionesJugador:List<Opcion>, \njugador:Jugador, modificador:Modificador)
    + asignarPuntajes()
    + reiniciarTurno(pregunta:Pregunta, manejador:Manejador)
    + cantidadDeRespuestas():int
}

AlgoHoot3 -down->"*" Jugador
AlgoHoot3 -down->"*" Pregunta
AlgoHoot3 -left->"1" Turno
AlgoHoot3 -up->"1" CriterioDeVictoria