@startuml PUNTAJE

skinparam classAttributeIconSize 0

abstract class Puntaje{
    ~ puntaje:int

    + {abstract} asignarPuntaje(respuesta:Respuesta)
    + asignarPuntajes(respuestas:List<Respuesta>)
    + {abstract} modificadorEsValido(modificador:Modificador):boolean
}

class Clasica extends Puntaje{
    ~ cantidadCorrectasEsperada:int

    + Clasica(cantidadCorrectasPregunta:int)
    + asignarPuntaje(respuesta:Respuesta)
    + modificadorEsValido(modificador:Usable):boolean
}

class ConPenalidad extends Puntaje{
    ~ puntajeIncorrecta:int

    + asignarPuntaje(respuesta:Respuesta)
    + modificadorEsValido(modificador:Usable):boolean
}

class Parcial {
    + asignarPuntaje(respuesta:Respuesta)
    + modificadorEsValido(modificador:Usable):boolean
}

Puntaje <|-up- Parcial