@startuml diagrama de clases
skinparam classAttributeIconSize 0
title Diagrama de clases

class Jugador{
    - nombre: String
    - puntaje: int
    ---
    + Jugador(nombre:String )
    + sumarPuntaje(puntaje:int )
    + obtenerPuntos():int
}

Class Respuesta {
    - contenido: List<String>
    - jugador: Jugador
    ---
    + Respuesta(contenido:List<String>,jugador:Jugador )
    + calcularCantidadRespuestas(respuestasCorrectas:List<String> ):Pair<Integer,Integer>
    + sumarPuntaje(puntaje:int )
}

 abstract class Puntaje {
     #totalCorrectas:int;
     #puntaje:int;
     + establecerTotalCorrectas(totalCorrectas:int )
     + asignarPuntaje(respuesta:Respuesta , respuestasIncorrectas:int , respuestasCorrectas:int )
}

class Clasica extends Puntaje{
     + asignarPuntaje([super])
}

class ConPenalidad extends Puntaje{
     + asignarPuntaje([super])
}

abstract class Pregunta {
    # enunciado: String
    # respuestasCorrectas: List<String>
    ---
    + Pregunta(enunciado: String, respuestasCorrectas:List<String> ,distribuidoraDePuntaje:DistribuidoraDePuntaje )
    + asignarPuntajes(respuestas:List<Respuesta>)
    + asignarPuntaje(Respuesta respuesta)
}

class VerdaderoFalso extends Pregunta {
    +VerdaderoOFalso([super])
}

class MultipleChoice extends Pregunta {
    #opciones: List<String>
    +MultipleChoice([super],opciones: List<String> )
    }

class Opcion {
    -descripcion :String
    -estado :Estado
    -equals(opcion :Opcion) :Bool
    ---
    {static}+ Opcion(descripcion :String, estado :Estado)
    {static}+ Opcion(descripcion :String, estado :Estado)
    +cambiarEstado(Estado estado)
    +esCorrecta():Bool
    +siIgualActualizarEstado(Opcion opcionCorrecta) :Bool
}

interface Estado{
    +esCorrecta():Bool
}

class Correcta implements Estado{
    +esCorrecta():Bool   
}

class Incorrecta implements Estado{
    +esCorrecta():Bool
}

Jugador "1" <- Respuesta
Pregunta -l-> "1" Puntaje
Respuesta <.. Pregunta
Puntaje ..> Respuesta
Opcion *-- Estado
Pregunta -d-> Opcion: "1..*"
Respuesta -> Opcion:"1..*"

@enduml
